### ISSUE TITLE
Game-breaking Bug in Final Fantasy I & II: Dawn of Souls

### ISSUE THREAD

**Issue by coltmay** [MiSTer-devel/GBA_MiSTer#125] opened 2022-06-04 04:48 UTC
Player cannot progress in overworld of Final Fantasy I, directions inverted/misinputed and walking through boundaries.

**To Reproduce**
After creating any group of 4 heros, exit town and walk in overworld

**Comment by birdybro** [comment] 2022-06-20 03:20
I can't reproduce this after trying a few times FYI. Make sure you go into the OSD, press right, then go to "Reset Settings", then reload the game and try it again. Maybe you had turbo on or some other setting was accidentally turned on in your config. That does sound pretty interesting though :)

**Comment by RobertPeip** [comment] 2022-08-11 14:56
any new results on that one?

**Comment by M-Walrus** [comment] 2022-08-13 08:54
I tried the USA version, JP/virtual console version, and EU release of this and cannot reproduce the reported issues.

**Comment by RobertPeip** [comment] 2022-08-13 09:06
Thanks, will close it

**Closed by RobertPeip** 2022-08-13 09:06 UTC
