### ISSUE TITLE
F-Zero Climax - Top left corner visual oddity (Machine Select)

### ISSUE THREAD

**Issue by R9delta** [MiSTer-devel/GBA_MiSTer#73] opened 2020-07-30 02:08 UTC
I’ve noticed for awhile on F-Zero Climax theres what I can best describe as a black flashing visual oddity on the top left corner of the screen when selecting your racer/machine. This does not happen on my real hardware though setting turbo to on also works around this issue.

**Comment by RobertPeip** [comment] 2020-07-30 19:36
Thanks for reporting. I will look into it as soon as have more time.

**Comment by RobertPeip** [comment] 2020-08-07 07:26
Unfortunatly debugging this one is very difficult. It seems to be an effect from some old menu.
If i create a savestate in the car select and load it back, the effect is gone and it only comes back when i go to mainmenu or select a car and cancel back.

**Comment by Chocobobobo** [comment] 2020-11-11 13:49
Issue still occurs with 201110 core.

**Comment by wwark** [comment] 2020-11-29 07:13
The issue is fixed with the last version 201120.
I think we can close this ticket.
Thanks @RobertPeip !

**Closed** 2020-11-30 06:21 UTC

**Comment by Thelypody** [comment] 2021-11-26 12:00
I'm afraid that there probably was a regression somewhere over time, as on core version 210718 there are flashing black diagonal lines in the top left corner of Machine Select screen.
