### ISSUE TITLE
Mario vs Donkey Kong graphical glitches

### ISSUE THREAD

**Issue by CrimsonAuthor** [MiSTer-devel/GBA_MiSTer#30] opened 2019-12-23 00:11 UTC
Several graphical glitches noticed in Mario vs Donkey Kong.
Name: Mario vs. Donkey Kong (USA, Australia).gba
CRC32: 25C394D1

The file select menu, chunks around the selected file do not fade in and out smoothly:
![main menu](https://i.imgur.com/sMZhiqn.jpg)

After selecting a level but before the tutorial animation, a frame or two of messed up graphics:
![select level](https://i.imgur.com/gfxNjWS.jpg)

**Comment by RobertPeip** [comment] 2019-12-23 12:31
For the first effect: this is not present in my emulator but i can reproduce on hardware.

What i found out: this is a alpha effect between Sprite 0 and BG3. BG3 has Prio 3 and Sprite has Prio 2 and Sprite is using Alpha, so it's normal Alpha effect between these two. It's using fading EVA/EVB coefficients with combinations using more then 100% color at the time of the bug.

So i highly assume the bug in gba_drawer_merge either in line 436-438 or 468-470

Maybe i find it with some more testing...

**Comment by RobertPeip** [comment] 2019-12-23 13:04
Further test: tonc testrom "bld_demo.gba" allows for arbitrary values for EVA and EVB and there everything seems fine.
So i'm not so sure anymore it has to do with the color mixing in alpha mode.

More strange for me, is that on save slot 1 and 2, there is a black pixel at the upper edge of the fading effect and i cannot imagine how this could get black at all...

**Comment by paulb-nl** [comment] 2019-12-29 00:27
Interestingly the pixels where blending is not working are all the backdrop color. This happens because prio2 in gba_drawer_merge starts with priority 0 by default and since the sprite (prio1) has priority 2 and the backdrop (prio2) now has priority 0 the blending is canceled.

Another issue is that those save slot borders are visible during full screen fade in and out. This is because special_effect_var is forced to 01 even though there is no 2nd target.

I am working on a fix for these and Street fighter Alpha 3 which is also a similar bug. I also checked how bld_demo.gba behaves on a real GBA to make sure it matches that behavior. mGBA does not apply the Brighten or Darken effect on the non-overlapping pixels of the obj which is incorrect. Higan seems to have the correct behavior. NoGba is mostly correct but incorrectly disables the obj blend when mode is 0.

Is this prio check here (prio2 >= prio1) really necessary?
https://github.com/MiSTer-devel/GBA_MiSTer/blob/1e07eca336adfbdcc22e275f02dc54e34f7425da/src/gba_drawer_merge.vhd#L410-L412

The priorities are already handled in clock cycle 1 and 2. In which scenario could firstprio_cycle3 have a lower priority (higher prio number) than secondprio_cycle3?

**Comment by RobertPeip** [comment] 2019-12-30 19:51
Good find. For the prio question: that can easily be a relic from all the development before. However even looking at it right now i'm not 100% sure that it's fully checked in the cycles before, so maybe i just added it as sanity check.

**Comment by RobertPeip** [comment] 2020-01-08 10:24
both issues are fixed in the current build

**Closed by RobertPeip** 2020-01-08 10:24 UTC
