### ISSUE TITLE
GBA's Quake port doesn't work with offical bios

### ISSUE THREAD

**Issue by WJWangSennheisermx500** [MiSTer-devel/GBA_MiSTer#128] opened 2022-06-25 14:59 UTC
I tryed the gba's quake port with latest gba rbf release and got white screen with offical gba bios

the real GBA hardware can play this game without any problem

if you download the game rom , it's called BOBBEE TEC_ABTE.gba

**Comment by RobertPeip** [comment] 2022-06-25 18:01
duplicate of this: https://github.com/MiSTer-devel/GBA_MiSTer/issues/126

**Closed by RobertPeip** 2022-06-25 18:01 UTC

**Comment by WJWangSennheisermx500** [comment] 2022-06-26 01:25
got it thanks
